### ISSUE TITLE
Reimplement Varun's changes and see if they pass Travis CI tests.

### ISSUE THREAD

**Issue by nopejpg** [nopejpg/expertiza#12]

**Comment by Cryptic-CMYK** [comment]
Travis CI failed as seen [here](https://travis-ci.org/expertiza/expertiza/builds/602456904?utm_medium=notification&utm_source=github_status). Investigation and testing of this failure have been documented in Issue #16, #17.

**Comment by Cryptic-CMYK** [comment]
Varun's implementation seems to somehow mess up the tree_display_controller, and therefore needs to be discarded for a different solution. The solution was instead of checking to see if the assignment is not within a submission window, to instead check to see if it is within a review window.
